apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: manager-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["backup.example.com"]
  resources:
    - backupstoragelocations
    - backupstoragelocations/status
    - backupstoragelocations/finalizers
    - backups
    - backups/status
    - backups/finalizers
    - clusterbackups
    - clusterbackups/status
    - clusterbackups/finalizers
    - restores
    - restores/status
    - restores/finalizers
    - clusterrestores
    - clusterrestores/status
    - clusterrestores/finalizers
    - remoteclusters
    - remoteclusters/status
    - remoteclusters/finalizers
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshots", "volumesnapshotcontents", "volumesnapshotclasses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
